Ticket4408 reduce calls to busapps
ISISComputingGroup/ExperimentDatabasePopulator pull request #2
Opened 2019-06-20 16:52 UTC by adamb56789

### Description of work

Reformatted to reduce number of calls to BusApps from (number_of_instruments * 3) per hour to 1 per hour. Previously there was a thread running for each instrument, now there is only one which populates all instruments every hour (no more multi-threading). The program is hopefully simpler now.

### Ticket

https://github.com/ISISComputingGroup/IBEX/issues/4408

### Acceptance criteria

- [ ] Calls BusApps much less
- [ ] Program behaves functionally identically to the previous version

### Unit tests

Adapted existing tests to work with the refactored code. Removed unnecessary tests and added some new ones.

### Documentation

https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Experimental-Database
The functionality hasn't changed, so I haven't needed to update the documentation.

---

#### Code Review

- [ ] Is the code of an acceptable quality?
- [ ] Do the changes function as described and is it robust?
- [ ] Have the changes been documented in the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev)?

### Final Steps
- [ ] Reviewer has moved the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev) entry for this ticket in the "Changes merged into master" section

2019-07-11 16:08 UTC, Alistair-McGann-Tessella requested changes
I really like that the gatherer has been factored out from the populator, this is a good new architecture.
The issues I've highlighted are mostly minor style points.

2019-07-11 16:08 UTC, Alistair-McGann-Tessella commented on exp_db_populator/gatherer.py
> +        data: The data from the website
I'm not sure which data this is referring to, can this be clarified in the docstring or with a more descriptive variable name?

2019-07-11 16:08 UTC, Alistair-McGann-Tessella commented on exp_db_populator/gatherer.py
> +    return list(filter(lambda x: x['instrument'] == inst_name, data))
This is fine, although a generator or list comprehension would be a more python-like way of doing this. Sticking to these style guidelines can make the code easier to read, although this is absolutely fine.

2019-07-11 16:08 UTC, Alistair-McGann-Tessella commented on exp_db_populator/gatherer.py
> +class Gatherer(threading.Thread):
This should have a docstring briefly explaining what the class does

2019-07-11 16:08 UTC, Alistair-McGann-Tessella commented on exp_db_populator/populator.py
> +    Populates the database with this experiment's data.
This docstring needs to be updated with the new arguments of this function

2019-07-11 16:08 UTC, Alistair-McGann-Tessella commented on tests/test_gatherer.py
> +        sleep(0.5)
Try to avoid using sleep in tests unless it is absolutely necessary. Is there another way of checking to make sure the gatherer has started?

2019-07-11 16:08 UTC, Alistair-McGann-Tessella commented on exp_db_populator/gatherer.py
> +def correct_name(old_name):
This appears to be duplicated from `main.py`. Do they both still need to exist?

2019-07-11 16:08 UTC, Alistair-McGann-Tessella commented on exp_db_populator/webservices_reader.py
> +        data_list (list): List of all data returned by the website.
`data_list` is not a descriptive variable name. What data does this represent?

2019-07-15 13:02 UTC, adamb56789 commented on exp_db_populator/gatherer.py
> +    return list(filter(lambda x: x['instrument'] == inst_name, data))
Changed to a list comprehension.

2019-07-15 13:04 UTC, adamb56789 commented on exp_db_populator/gatherer.py
> +        data: The data from the website
Changed variable name and added to docstrings.

2019-07-15 13:07 UTC, adamb56789 commented on exp_db_populator/gatherer.py
> +class Gatherer(threading.Thread):
Added a docstring.

2019-07-15 13:13 UTC, adamb56789 commented on exp_db_populator/populator.py
> +    Populates the database with this experiment's data.
Updated the docstring.

2019-07-15 13:18 UTC, adamb56789 commented on exp_db_populator/gatherer.py
> +def correct_name(old_name):
Removed it from `main.py` as it wasn't used there.

2019-07-15 13:21 UTC, adamb56789 commented on exp_db_populator/webservices_reader.py
> +        data_list (list): List of all data returned by the website.
Renamed to `instrument_data_list` and updated docstring.

2019-07-15 13:42 UTC, adamb56789 commented on tests/test_gatherer.py
> +        sleep(0.5)
Replaced this with a join that waits until the gatherer terminates.

2019-07-24 12:44 UTC, Alistair-McGann-Tessella approved these changes

2019-07-24 12:44 UTC, merged